import unittest
import requests
from tokenization import *

res = requests.get("https://github.com/python/cpython/pull/24239.diff")

example = {
 #'diff': 'diff --git a/Lib/ctypes/test/test_parameters.py b/Lib/ctypes/test/test_parameters.py\nindex e4c25fd880ce..531894fdec83 100644\n--- a/Lib/ctypes/test/test_parameters.py\n+++ b/Lib/ctypes/test/test_parameters.py\n@@ -201,6 +201,49 @@ def __dict__(self):\n         with self.assertRaises(ZeroDivisionError):\n             WorseStruct().__setstate__({}, b\'foo\')\n \n+    def test_parameter_repr(self):\n+        from ctypes import (\n+            c_bool,\n+            c_char,\n+            c_wchar,\n+            c_byte,\n+            c_ubyte,\n+            c_short,\n+            c_ushort,\n+            c_int,\n+            c_uint,\n+            c_long,\n+            c_ulong,\n+            c_longlong,\n+            c_ulonglong,\n+            c_float,\n+            c_double,\n+            c_longdouble,\n+            c_char_p,\n+            c_wchar_p,\n+            c_void_p,\n+        )\n+        self.assertRegex(repr(c_bool.from_param(True)), r"^<cparam \'\\?\' at 0x[A-Fa-f0-9]+>$")\n+        self.assertEqual(repr(c_char.from_param(97)), "<cparam \'c\' (\'a\')>")\n+        self.assertRegex(repr(c_wchar.from_param(\'a\')), r"^<cparam \'u\' at 0x[A-Fa-f0-9]+>$")\n+        self.assertEqual(repr(c_byte.from_param(98)), "<cparam \'b\' (98)>")\n+        self.assertEqual(repr(c_ubyte.from_param(98)), "<cparam \'B\' (98)>")\n+        self.assertEqual(repr(c_short.from_param(511)), "<cparam \'h\' (511)>")\n+        self.assertEqual(repr(c_ushort.from_param(511)), "<cparam \'H\' (511)>")\n+        self.assertRegex(repr(c_int.from_param(20000)), r"^<cparam \'[li]\' \\(20000\\)>$")\n+        self.assertRegex(repr(c_uint.from_param(20000)), r"^<cparam \'[LI]\' \\(20000\\)>$")\n+        self.assertRegex(repr(c_long.from_param(20000)), r"^<cparam \'[li]\' \\(20000\\)>$")\n+        self.assertRegex(repr(c_ulong.from_param(20000)), r"^<cparam \'[LI]\' \\(20000\\)>$")\n+        self.assertRegex(repr(c_longlong.from_param(20000)), r"^<cparam \'[liq]\' \\(20000\\)>$")\n+        self.assertRegex(repr(c_ulonglong.from_param(20000)), r"^<cparam \'[LIQ]\' \\(20000\\)>$")\n+        self.assertEqual(repr(c_float.from_param(1.5)), "<cparam \'f\' (1.5)>")\n+        self.assertEqual(repr(c_double.from_param(1.5)), "<cparam \'d\' (1.5)>")\n+        self.assertEqual(repr(c_double.from_param(1e300)), "<cparam \'d\' (1e+300)>")\n+        self.assertRegex(repr(c_longdouble.from_param(1.5)), r"^<cparam (\'d\' \\(1.5\\)|\'g\' at 0x[A-Fa-f0-9]+)>$")\n+        self.assertRegex(repr(c_char_p.from_param(b\'hihi\')), "^<cparam \'z\' \\(0x[A-Fa-f0-9]+\\)>$")\n+        self.assertRegex(repr(c_wchar_p.from_param(\'hihi\')), "^<cparam \'Z\' \\(0x[A-Fa-f0-9]+\\)>$")\n+        self.assertRegex(repr(c_void_p.from_param(0x12)), r"^<cparam \'P\' \\(0x0*12\\)>$")\n+\n ################################################################\n \n if __name__ == \'__main__\':\ndiff --git a/Misc/NEWS.d/next/Security/2021-01-18-09-27-31.bpo-42938.4Zn4Mp.rst b/Misc/NEWS.d/next/Security/2021-01-18-09-27-31.bpo-42938.4Zn4Mp.rst\nnew file mode 100644\nindex 000000000000..7df65a156fea\n--- /dev/null\n+++ b/Misc/NEWS.d/next/Security/2021-01-18-09-27-31.bpo-42938.4Zn4Mp.rst\n@@ -0,0 +1,2 @@\n+Avoid static buffers when computing the repr of :class:`ctypes.c_double` and\n+:class:`ctypes.c_longdouble` values.\ndiff --git a/Modules/_ctypes/callproc.c b/Modules/_ctypes/callproc.c\nindex 40a05a44edd4..56ccc2f1e0b5 100644\n--- a/Modules/_ctypes/callproc.c\n+++ b/Modules/_ctypes/callproc.c\n@@ -487,58 +487,47 @@ is_literal_char(unsigned char c)\n static PyObject *\n PyCArg_repr(PyCArgObject *self)\n {\n-    char buffer[256];\n     switch(self->tag) {\n     case \'b\':\n     case \'B\':\n-        sprintf(buffer, "<cparam \'%c\' (%d)>",\n+        return PyUnicode_FromFormat("<cparam \'%c\' (%d)>",\n             self->tag, self->value.b);\n-        break;\n     case \'h\':\n     case \'H\':\n-        sprintf(buffer, "<cparam \'%c\' (%d)>",\n+        return PyUnicode_FromFormat("<cparam \'%c\' (%d)>",\n             self->tag, self->value.h);\n-        break;\n     case \'i\':\n     case \'I\':\n-        sprintf(buffer, "<cparam \'%c\' (%d)>",\n+        return PyUnicode_FromFormat("<cparam \'%c\' (%d)>",\n             self->tag, self->value.i);\n-        break;\n     case \'l\':\n     case \'L\':\n-        sprintf(buffer, "<cparam \'%c\' (%ld)>",\n+        return PyUnicode_FromFormat("<cparam \'%c\' (%ld)>",\n             self->tag, self->value.l);\n-        break;\n \n     case \'q\':\n     case \'Q\':\n-        sprintf(buffer,\n-#ifdef MS_WIN32\n-            "<cparam \'%c\' (%I64d)>",\n-#else\n-            "<cparam \'%c\' (%lld)>",\n-#endif\n+        return PyUnicode_FromFormat("<cparam \'%c\' (%lld)>",\n             self->tag, self->value.q);\n-        break;\n     case \'d\':\n-        sprintf(buffer, "<cparam \'%c\' (%f)>",\n-            self->tag, self->value.d);\n-        break;\n-    case \'f\':\n-        sprintf(buffer, "<cparam \'%c\' (%f)>",\n-            self->tag, self->value.f);\n-        break;\n-\n+    case \'f\': {\n+        PyObject *f = PyFloat_FromDouble((self->tag == \'f\') ? self->value.f : self->value.d);\n+        if (f == NULL) {\n+            return NULL;\n+        }\n+        PyObject *result = PyUnicode_FromFormat("<cparam \'%c\' (%R)>", self->tag, f);\n+        Py_DECREF(f);\n+        return result;\n+    }\n     case \'c\':\n         if (is_literal_char((unsigned char)self->value.c)) {\n-            sprintf(buffer, "<cparam \'%c\' (\'%c\')>",\n+            return PyUnicode_FromFormat("<cparam \'%c\' (\'%c\')>",\n                 self->tag, self->value.c);\n         }\n         else {\n-            sprintf(buffer, "<cparam \'%c\' (\'\\\\x%02x\')>",\n+            return PyUnicode_FromFormat("<cparam \'%c\' (\'\\\\x%02x\')>",\n                 self->tag, (unsigned char)self->value.c);\n         }\n-        break;\n \n /* Hm, are these \'z\' and \'Z\' codes useful at all?\n    Shouldn\'t they be replaced by the functionality of c_string\n@@ -547,22 +536,20 @@ PyCArg_repr(PyCArgObject *self)\n     case \'z\':\n     case \'Z\':\n     case \'P\':\n-        sprintf(buffer, "<cparam \'%c\' (%p)>",\n+        return PyUnicode_FromFormat("<cparam \'%c\' (%p)>",\n             self->tag, self->value.p);\n         break;\n \n     default:\n         if (is_literal_char((unsigned char)self->tag)) {\n-            sprintf(buffer, "<cparam \'%c\' at %p>",\n+            return PyUnicode_FromFormat("<cparam \'%c\' at %p>",\n                 (unsigned char)self->tag, (void *)self);\n         }\n         else {\n-            sprintf(buffer, "<cparam 0x%02x at %p>",\n+            return PyUnicode_FromFormat("<cparam 0x%02x at %p>",\n                 (unsigned char)self->tag, (void *)self);\n         }\n-        break;\n     }\n-    return PyUnicode_FromString(buffer);\n }\n \n static PyMemberDef PyCArgType_members[] = {',
 'diff': res.text + "\n",
 'lexer': defaultdict(list,
             {6: [(Token.Text, '        '),
               (Token.Keyword, 'with'),
               (Token.Text, ' '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRaises'),
               (Token.Punctuation, '('),
               (Token.Name.Exception, 'ZeroDivisionError'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              7: [(Token.Text, '            '),
               (Token.Name, 'WorseStruct'),
               (Token.Punctuation, '('),
               (Token.Punctuation, ')'),
               (Token.Operator, '.'),
               (Token.Name, '__setstate__'),
               (Token.Punctuation, '('),
               (Token.Punctuation, '{'),
               (Token.Punctuation, '}'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Affix, 'b'),
               (Token.Literal.String.Single, "'"),
               (Token.Literal.String.Single, 'foo'),
               (Token.Literal.String.Single, "'"),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              8: [(Token.Text.Whitespace, '\n')],
              9: [(Token.Text, '    '),
               (Token.Keyword, 'def'),
               (Token.Text, ' '),
               (Token.Name.Function, 'test_parameter_repr'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              10: [(Token.Text, '        '),
               (Token.Keyword.Namespace, 'from'),
               (Token.Text, ' '),
               (Token.Name.Namespace, 'ctypes'),
               (Token.Text, ' '),
               (Token.Keyword.Namespace, 'import'),
               (Token.Text, ' '),
               (Token.Punctuation, '('),
               (Token.Text.Whitespace, '\n')],
              11: [(Token.Text, '            '),
               (Token.Name, 'c_bool'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              12: [(Token.Text, '            '),
               (Token.Name, 'c_char'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              13: [(Token.Text, '            '),
               (Token.Name, 'c_wchar'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              14: [(Token.Text, '            '),
               (Token.Name, 'c_byte'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              15: [(Token.Text, '            '),
               (Token.Name, 'c_ubyte'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              16: [(Token.Text, '            '),
               (Token.Name, 'c_short'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              17: [(Token.Text, '            '),
               (Token.Name, 'c_ushort'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              18: [(Token.Text, '            '),
               (Token.Name, 'c_int'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              19: [(Token.Text, '            '),
               (Token.Name, 'c_uint'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              20: [(Token.Text, '            '),
               (Token.Name, 'c_long'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              21: [(Token.Text, '            '),
               (Token.Name, 'c_ulong'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              22: [(Token.Text, '            '),
               (Token.Name, 'c_longlong'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              23: [(Token.Text, '            '),
               (Token.Name, 'c_ulonglong'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              24: [(Token.Text, '            '),
               (Token.Name, 'c_float'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              25: [(Token.Text, '            '),
               (Token.Name, 'c_double'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              26: [(Token.Text, '            '),
               (Token.Name, 'c_longdouble'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              27: [(Token.Text, '            '),
               (Token.Name, 'c_char_p'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              28: [(Token.Text, '            '),
               (Token.Name, 'c_wchar_p'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              29: [(Token.Text, '            '),
               (Token.Name, 'c_void_p'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              30: [(Token.Text, '        '),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              31: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRegex'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_bool'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Keyword.Constant, 'True'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Affix, 'r'),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '^<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, '?'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' at 0x[A-Fa-f0-9]+>$'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              32: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertEqual'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_char'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Integer, '97'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'c'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' ('),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'a'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ')>'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              33: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRegex'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_wchar'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.String.Single, "'"),
               (Token.Literal.String.Single, 'a'),
               (Token.Literal.String.Single, "'"),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Affix, 'r'),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '^<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'u'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' at 0x[A-Fa-f0-9]+>$'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              34: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertEqual'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_byte'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Integer, '98'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'b'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' (98)>'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              35: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertEqual'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_ubyte'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Integer, '98'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'B'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' (98)>'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              36: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertEqual'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_short'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Integer, '511'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'h'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' (511)>'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              37: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertEqual'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_ushort'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Integer, '511'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'H'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' (511)>'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              38: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRegex'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_int'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Integer, '20000'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Affix, 'r'),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '^<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, '[li]'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' '),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, '(20000'),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, ')>$'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              39: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRegex'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_uint'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Integer, '20000'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Affix, 'r'),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '^<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, '[LI]'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' '),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, '(20000'),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, ')>$'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              40: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRegex'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_long'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Integer, '20000'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Affix, 'r'),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '^<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, '[li]'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' '),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, '(20000'),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, ')>$'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              41: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRegex'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_ulong'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Integer, '20000'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Affix, 'r'),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '^<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, '[LI]'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' '),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, '(20000'),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, ')>$'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              42: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRegex'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_longlong'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Integer, '20000'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Affix, 'r'),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '^<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, '[liq]'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' '),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, '(20000'),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, ')>$'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              43: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRegex'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_ulonglong'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Integer, '20000'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Affix, 'r'),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '^<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, '[LIQ]'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' '),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, '(20000'),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, ')>$'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              44: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertEqual'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_float'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Float, '1.5'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'f'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' (1.5)>'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              45: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertEqual'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_double'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Float, '1.5'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'd'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' (1.5)>'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              46: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertEqual'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_double'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Float, '1e300'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'd'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' (1e+300)>'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              47: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRegex'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_longdouble'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Float, '1.5'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Affix, 'r'),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '^<cparam ('),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'd'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' '),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, '(1.5'),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, ')|'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'g'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' at 0x[A-Fa-f0-9]+)>$'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              48: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRegex'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_char_p'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.String.Affix, 'b'),
               (Token.Literal.String.Single, "'"),
               (Token.Literal.String.Single, 'hihi'),
               (Token.Literal.String.Single, "'"),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '^<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'z'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' '),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, '(0x[A-Fa-f0-9]+'),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, ')>$'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              49: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRegex'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_wchar_p'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.String.Single, "'"),
               (Token.Literal.String.Single, 'hihi'),
               (Token.Literal.String.Single, "'"),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '^<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'Z'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' '),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, '(0x[A-Fa-f0-9]+'),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, ')>$'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              50: [(Token.Text, '        '),
               (Token.Name.Builtin.Pseudo, 'self'),
               (Token.Operator, '.'),
               (Token.Name, 'assertRegex'),
               (Token.Punctuation, '('),
               (Token.Name.Builtin, 'repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'c_void_p'),
               (Token.Operator, '.'),
               (Token.Name, 'from_param'),
               (Token.Punctuation, '('),
               (Token.Literal.Number.Hex, '0x12'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ','),
               (Token.Text, ' '),
               (Token.Literal.String.Affix, 'r'),
               (Token.Literal.String.Double, '"'),
               (Token.Literal.String.Double, '^<cparam '),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, 'P'),
               (Token.Literal.String.Double, "'"),
               (Token.Literal.String.Double, ' '),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, '(0x0*12'),
               (Token.Literal.String.Double, '\\'),
               (Token.Literal.String.Double, ')>$'),
               (Token.Literal.String.Double, '"'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              51: [(Token.Text.Whitespace, '\n')],
              52: [(Token.Comment.Single,
                '################################################################'),
               (Token.Text.Whitespace, '\n')],
              53: [(Token.Text.Whitespace, '\n')],
              54: [(Token.Keyword, 'if'),
               (Token.Text, ' '),
               (Token.Name.Variable.Magic, '__name__'),
               (Token.Text, ' '),
               (Token.Operator, '=='),
               (Token.Text, ' '),
               (Token.Literal.String.Single, "'"),
               (Token.Literal.String.Single, '__main__'),
               (Token.Literal.String.Single, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              61: [(Token.Text,
                'Avoid static buffers when computing the repr of '),
               (Token.Name.Attribute, ':class:'),
               (Token.Name.Variable, '`ctypes.c_double`'),
               (Token.Text, ' and'),
               (Token.Text.Whitespace, '\n')],
              62: [(Token.Name.Attribute, ':class:'),
               (Token.Name.Variable, '`ctypes.c_longdouble`'),
               (Token.Text, ' values.'),
               (Token.Text.Whitespace, '\n')],
              68: [(Token.Keyword, 'static'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyObject'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, '*'),
               (Token.Text.Whitespace, '\n')],
              69: [(Token.Name.Function, 'PyCArg_repr'),
               (Token.Punctuation, '('),
               (Token.Name, 'PyCArgObject'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, '*'),
               (Token.Name, 'self'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, '\n')],
              70: [(Token.Punctuation, '{'), (Token.Text.Whitespace, '\n')],
              71: [(Token.Text.Whitespace, '    '),
               (Token.Keyword.Type, 'char'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'buffer'),
               (Token.Punctuation, '['),
               (Token.Literal.Number.Integer, '256'),
               (Token.Punctuation, ']'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              72: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'switch'),
               (Token.Punctuation, '('),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '{'),
               (Token.Text.Whitespace, '\n')],
              73: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'b'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              74: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'B'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              75: [(Token.Text.Whitespace, '        '),
               (Token.Name, 'sprintf'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%d)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              76: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyUnicode_FromFormat'),
               (Token.Punctuation, '('),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%d)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              77: [(Token.Text.Whitespace, '            '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'b'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              78: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'break'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              79: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'h'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              80: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'H'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              81: [(Token.Text.Whitespace, '        '),
               (Token.Name, 'sprintf'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%d)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              82: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyUnicode_FromFormat'),
               (Token.Punctuation, '('),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%d)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              83: [(Token.Text.Whitespace, '            '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'h'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              84: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'break'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              85: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'i'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              86: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'I'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              87: [(Token.Text.Whitespace, '        '),
               (Token.Name, 'sprintf'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%d)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              88: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyUnicode_FromFormat'),
               (Token.Punctuation, '('),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%d)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              89: [(Token.Text.Whitespace, '            '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'i'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              90: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'break'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              91: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'l'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              92: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'L'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              93: [(Token.Text.Whitespace, '        '),
               (Token.Name, 'sprintf'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%ld)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              94: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyUnicode_FromFormat'),
               (Token.Punctuation, '('),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%ld)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              95: [(Token.Text.Whitespace, '            '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'l'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              96: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'break'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              97: [(Token.Text.Whitespace, '\n')],
              98: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'q'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              99: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'Q'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              100: [(Token.Text.Whitespace, '        '),
               (Token.Name, 'sprintf'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              101: [(Token.Comment.Preproc, '#'),
               (Token.Comment.Preproc, 'ifdef MS_WIN32'),
               (Token.Comment.Preproc, '\n')],
              102: [(Token.Text.Whitespace, '            '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%I64d)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              103: [(Token.Comment.Preproc, '#'),
               (Token.Comment.Preproc, 'else'),
               (Token.Comment.Preproc, '\n')],
              104: [(Token.Text.Whitespace, '            '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%lld)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              105: [(Token.Comment.Preproc, '#'),
               (Token.Comment.Preproc, 'endif'),
               (Token.Comment.Preproc, '\n')],
              106: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyUnicode_FromFormat'),
               (Token.Punctuation, '('),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%lld)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              107: [(Token.Text.Whitespace, '            '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'q'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              108: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'break'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              109: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'd'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              110: [(Token.Text.Whitespace, '        '),
               (Token.Name, 'sprintf'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%f)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              111: [(Token.Text.Whitespace, '            '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'd'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              112: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'break'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              113: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'f'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              114: [(Token.Text.Whitespace, '        '),
               (Token.Name, 'sprintf'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%f)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              115: [(Token.Text.Whitespace, '            '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'f'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              116: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'break'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              117: [(Token.Text.Whitespace, '\n')],
              118: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'f'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '{'),
               (Token.Text.Whitespace, '\n')],
              119: [(Token.Text.Whitespace, '        '),
               (Token.Name, 'PyObject'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, '*'),
               (Token.Name, 'f'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, '='),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyFloat_FromDouble'),
               (Token.Punctuation, '('),
               (Token.Punctuation, '('),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, '='),
               (Token.Operator, '='),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'f'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, '?'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'f'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, ':'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'd'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              120: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'if'),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '('),
               (Token.Name, 'f'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, '='),
               (Token.Operator, '='),
               (Token.Text.Whitespace, ' '),
               (Token.Name.Builtin, 'NULL'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '{'),
               (Token.Text.Whitespace, '\n')],
              121: [(Token.Text.Whitespace, '            '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name.Builtin, 'NULL'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              122: [(Token.Text.Whitespace, '        '),
               (Token.Punctuation, '}'),
               (Token.Text.Whitespace, '\n')],
              123: [(Token.Text.Whitespace, '        '),
               (Token.Name, 'PyObject'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, '*'),
               (Token.Name, 'result'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, '='),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyUnicode_FromFormat'),
               (Token.Punctuation, '('),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%R)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'f'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              124: [(Token.Text.Whitespace, '        '),
               (Token.Name, 'Py_DECREF'),
               (Token.Punctuation, '('),
               (Token.Name, 'f'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              125: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'result'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              126: [(Token.Text.Whitespace, '    '),
               (Token.Punctuation, '}'),
               (Token.Text.Whitespace, '\n')],
              127: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'c'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              128: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'if'),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '('),
               (Token.Name, 'is_literal_char'),
               (Token.Punctuation, '('),
               (Token.Punctuation, '('),
               (Token.Keyword.Type, 'unsigned'),
               (Token.Text.Whitespace, ' '),
               (Token.Keyword.Type, 'char'),
               (Token.Punctuation, ')'),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'c'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '{'),
               (Token.Text.Whitespace, '\n')],
              129: [(Token.Text.Whitespace, '            '),
               (Token.Name, 'sprintf'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' ('%c')>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              130: [(Token.Text.Whitespace, '            '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyUnicode_FromFormat'),
               (Token.Punctuation, '('),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' ('%c')>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              131: [(Token.Text.Whitespace, '                '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'c'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              132: [(Token.Text.Whitespace, '        '),
               (Token.Punctuation, '}'),
               (Token.Text.Whitespace, '\n')],
              133: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'else'),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '{'),
               (Token.Text.Whitespace, '\n')],
              134: [(Token.Text.Whitespace, '            '),
               (Token.Name, 'sprintf'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' ('"),
               (Token.Literal.String.Escape, '\\\\'),
               (Token.Literal.String, "x%02x')>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              135: [(Token.Text.Whitespace, '            '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyUnicode_FromFormat'),
               (Token.Punctuation, '('),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' ('"),
               (Token.Literal.String.Escape, '\\\\'),
               (Token.Literal.String, "x%02x')>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              136: [(Token.Text.Whitespace, '                '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '('),
               (Token.Keyword.Type, 'unsigned'),
               (Token.Text.Whitespace, ' '),
               (Token.Keyword.Type, 'char'),
               (Token.Punctuation, ')'),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'c'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              137: [(Token.Text.Whitespace, '        '),
               (Token.Punctuation, '}'),
               (Token.Text.Whitespace, '\n')],
              138: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'break'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              139: [(Token.Text.Whitespace, '\n')],
              140: [(Token.Comment.Multiline,
                "/* Hm, are these 'z' and 'Z' codes useful at all?\n   Shouldn't they be replaced by the functionality of c_string\n")],
              143: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'z'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              144: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'Z'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              145: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'case'),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String.Char, "'"),
               (Token.Literal.String.Char, 'P'),
               (Token.Literal.String.Char, "'"),
               (Token.Punctuation, ':'),
               (Token.Text.Whitespace, '\n')],
              146: [(Token.Text.Whitespace, '        '),
               (Token.Name, 'sprintf'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%p)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              147: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyUnicode_FromFormat'),
               (Token.Punctuation, '('),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' (%p)>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              148: [(Token.Text.Whitespace, '            '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'value'),
               (Token.Punctuation, '.'),
               (Token.Name, 'p'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              149: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'break'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              150: [(Token.Text.Whitespace, '\n')],
              151: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'default'),
               (Token.Operator, ':'),
               (Token.Text.Whitespace, '\n')],
              152: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'if'),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '('),
               (Token.Name, 'is_literal_char'),
               (Token.Punctuation, '('),
               (Token.Punctuation, '('),
               (Token.Keyword.Type, 'unsigned'),
               (Token.Text.Whitespace, ' '),
               (Token.Keyword.Type, 'char'),
               (Token.Punctuation, ')'),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ')'),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '{'),
               (Token.Text.Whitespace, '\n')],
              153: [(Token.Text.Whitespace, '            '),
               (Token.Name, 'sprintf'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' at %p>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              154: [(Token.Text.Whitespace, '            '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyUnicode_FromFormat'),
               (Token.Punctuation, '('),
               (Token.Literal.String, '"'),
               (Token.Literal.String, "<cparam '%c' at %p>"),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              155: [(Token.Text.Whitespace, '                '),
               (Token.Punctuation, '('),
               (Token.Keyword.Type, 'unsigned'),
               (Token.Text.Whitespace, ' '),
               (Token.Keyword.Type, 'char'),
               (Token.Punctuation, ')'),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '('),
               (Token.Keyword.Type, 'void'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, '*'),
               (Token.Punctuation, ')'),
               (Token.Name, 'self'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              156: [(Token.Text.Whitespace, '        '),
               (Token.Punctuation, '}'),
               (Token.Text.Whitespace, '\n')],
              157: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'else'),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '{'),
               (Token.Text.Whitespace, '\n')],
              158: [(Token.Text.Whitespace, '            '),
               (Token.Name, 'sprintf'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Literal.String, '"'),
               (Token.Literal.String, '<cparam 0x%02x at %p>'),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              159: [(Token.Text.Whitespace, '            '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyUnicode_FromFormat'),
               (Token.Punctuation, '('),
               (Token.Literal.String, '"'),
               (Token.Literal.String, '<cparam 0x%02x at %p>'),
               (Token.Literal.String, '"'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, '\n')],
              160: [(Token.Text.Whitespace, '                '),
               (Token.Punctuation, '('),
               (Token.Keyword.Type, 'unsigned'),
               (Token.Text.Whitespace, ' '),
               (Token.Keyword.Type, 'char'),
               (Token.Punctuation, ')'),
               (Token.Name, 'self'),
               (Token.Operator, '-'),
               (Token.Operator, '>'),
               (Token.Name, 'tag'),
               (Token.Punctuation, ','),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '('),
               (Token.Keyword.Type, 'void'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, '*'),
               (Token.Punctuation, ')'),
               (Token.Name, 'self'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              161: [(Token.Text.Whitespace, '        '),
               (Token.Punctuation, '}'),
               (Token.Text.Whitespace, '\n')],
              162: [(Token.Text.Whitespace, '        '),
               (Token.Keyword, 'break'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              163: [(Token.Text.Whitespace, '    '),
               (Token.Punctuation, '}'),
               (Token.Text.Whitespace, '\n')],
              164: [(Token.Text.Whitespace, '    '),
               (Token.Keyword, 'return'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyUnicode_FromString'),
               (Token.Punctuation, '('),
               (Token.Name, 'buffer'),
               (Token.Punctuation, ')'),
               (Token.Punctuation, ';'),
               (Token.Text.Whitespace, '\n')],
              165: [(Token.Punctuation, '}'), (Token.Text.Whitespace, '\n')],
              166: [(Token.Text.Whitespace, '\n')],
              167: [(Token.Keyword, 'static'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyMemberDef'),
               (Token.Text.Whitespace, ' '),
               (Token.Name, 'PyCArgType_members'),
               (Token.Punctuation, '['),
               (Token.Punctuation, ']'),
               (Token.Text.Whitespace, ' '),
               (Token.Operator, '='),
               (Token.Text.Whitespace, ' '),
               (Token.Punctuation, '{'),
               (Token.Text.Whitespace, '\n')]}),
 'files': ['a/Lib/ctypes/test/test_parameters.py',
  'a/Misc/NEWS.d/next/Security/2021-01-18-09-27-31.bpo-42938.4Zn4Mp.rst',
  'a/Modules/_ctypes/callproc.c'],
 'filestolines': {'a/Lib/ctypes/test/test_parameters.py': 1,
  'a/Misc/NEWS.d/next/Security/2021-01-18-09-27-31.bpo-42938.4Zn4Mp.rst': 55,
  'a/Modules/_ctypes/callproc.c': 63},
 'possible_wrong_numbering': []}

diff_lines = [line.decode(res.encoding) + "\n" for line in res.iter_lines()]


class TestFunctions(unittest.TestCase):
    def test_tokenizeCodeInDiff(self):
        self.assertEqual(tokenizeCodeInDiff(diff_lines), example)


unittest.main(argv=[''], verbosity=2, exit=False)
